baseURL = "https://taskwarrior.org"
languageCode = "en-us"
title = "Taskwarrior"
theme = "bootstrap"
publishDir = "html"

[params]
description = "Taskwarrior is Free and Open Source Software that manages your TODO list from the command line."

[taxonomies]

[markup]
    [markup.tableOfContents]
        endLevel = 2
        ordered = false
